spring:
  kafka:
    consumer:
      bootstrap-servers: kafka1:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: e903-data-processes
  data:
    mongodb:
      uri: mongodb://mongo:27017/e903


weichat-minapp:
  appId: wxae79b5f1437e2ac9
  secret: 0b0da789af03cb607bbcef415093ec9d



topic: app-n256

logging:
  config: classpath:logback-pro.xml

