spring:
  datasource:
    url: jdbc:mysql://mysql:3306/goshopping?characterEncoding=utf-8
    username: goshopping
    password: goshoppingpasswd..
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rinlink.goshopping.model
  type-handlers-package: com.rinlink.goshopping.typehandler




alipay-app2-client:
  # 应用2.0
  gateway: https://openapi.alipay.com/gateway.do
  appId: 2019053065406795
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCVlrwfJLKd6m09MCAoTixbnQq5omYHreA5TlD+K32nN2UQIYBAPqV9i3b8FzJyLUGfR4hEnHmMXcIQM4ynOviAnvacPZgi4sQ9kuSM5z8AURSzA66GBRt05/fOf8cGnG2F4kQbsgYqkbNz9RzXN2jz38BXdtg1e4Fkq3Xv+ncXYqVcx7O+QUs7K1jvS44Wye1ddfHgrfBTDVxRX4mRNX6pB05Wzl+qJyBUnWkUq600o40tb3X3Sw/Mg5+J0KmGKmU+viGGWevcEbacKlIC6qWcah/1ouGVUcikCDVwpGZ603rWfiTfO+Bb/EMMuLe3KKaOZR0ZMMVsdjPTO6xN555DAgMBAAECggEAYHvkBPZnmwGcyg2jgDvD0qd9RnTf+G4HJQ9FoFsu5c8OCZSCI24E0fBFo53WtNxJ6lF6LD79CzNiO470VtzrchKWH/p+iWnYh5qafeOduDeT8U8bn2fl6MbCCFhUaAg3gFaL9Y0i+wwVQmLD4nDj6gDVD9Ug6YYq1GLfZBUaAWNkLBsRX2JU2wNFcOaSmK3o3SEqBoHOkX850HPeYNDO1uVWXZbHoThtftLc7QyI4jSk0nnW1y+6+SKGM2WJAEGKVjZnIGj4L6uM4LpuQwQ2GleRNP3WKxAAzInNjdpru7Xep+x2Ea7LX0+QqiQmITsaXgkkWmqdok0GLa5GKXLTCQKBgQD5p6eIPZsI0sSAO7WPRiKCsaGyuFLbrsB+P3vpQnojisDFCIL5vmmw48oEG20I8Nwgn4Epuw/c3PtYxMuzfpMxCiQj8+OaWtswlDoUWEC4S9qheh4EHDdqZfBJMK8QCXrxVfGwM7utLa0hG5Te9jzKroFVGukb+34OxprboOhf9QKBgQCZZAOYFKnwqmzdErEZiIcwRXrTmJ0ifYrFi1wJLAE0J5tkyaIoSYyw5OoFkkmDS+1qBzzhcNZxD4MMRgwoz9QKYIdH7kj9jnD0xbTWB+nnUNQ43RC5o61BTxn/4tCSvj/YC7ZlC03Um3QhPDODKNmF9Hi5Xs2ftaRnPSjWZPu6VwKBgQDz+ptoMsSDT+9HXpLlrOXnEY9zqF0ZYeOuvX3sDNJuT5hqNhJB3YtOmp5/ewoItdJ6c0b4MF6lOrTMIK7uAKH6R+3f0OY6n9Yb2JAV99VwBnloW35gB+9EJNE5xcEgDBPBLHug9j3QVZYfh+PqLXxlmzq7oCv188ZSzFbkkpDlzQKBgD6OGiUgcDm01xbFc7ItCqz1+ORoPdT+C+UKM2uOJaOGb4oH7PivHhBaGtJQ2WgRQ+5Uq1BpOxr6r4AG5RiTwS7GNQVxuRSmzYwVQO10ZsCuJw5VoWeDx7l1r+26K0NdER5jkGve00vcZdzT91ILC8Lkc4NtlUAHzNdJiuj8X+ibAoGBAIE6RJ3cGIwVby3VRiPSHFUeqE2yp30i6/q011TpYauQoUumJngll2EGWsLsoC9NffArC/fek6Gklybz8ciiOZ4fFuY10quNQEoeRemWkYmPWr1ke+OnCeuueYtctpLUt4EnMnTXDCTQD4krINEVZd108eFOI8ES1pmrXpCKRqoQ
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlrSiZe+OPD94yMdX8R8Tts3Mhn4aqLqFKYgtRIdpClbbNLbhr3YW+bqw3m02jSkcFjg0rdkJ/TWkWlmkteAAReqpcEUgwJ3qEsMUi8nHClT9/DC2ajrlVsUKvtyg13U6C39B98UjLShXa8aAIrpclngE1GplpsiABL1K/aWM++1YSWpLTeMFAElW+6d27367KHoSmsiv26IcJY91gUXjjgSWmdeT8+rSW82VSEaZ9goIvswOCI2JKnnnS/AX5vmt4FzV/AcSlMaHgRc7pfa/Fo+S+s7XNqxzjbrjhAsTs6YNhNDgFUM0QrZ5S3sr6FpYnfjzydcrPPh0Yn8WkViHzwIDAQAB
  signType: RSA2



rinlink:
   alipay-client:
     #小程序
     gateway: https://openapi.alipay.com/gateway.do
     appId: 2019041963949949
     privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqhbGYQIXfXkeG8VfIOLzv18PUd0qlZx1KBf6NiiupsDK7MVqggRb/PGPuHandSJZgR39Io99S5nSDHy/K0EBhJTxrNnaQK4IjvnsvwIc2iS6a0ugq2jsZg32JjCgpMNrmaxWmAtxwYB/8bmsT6JXCocFWfKImqhu/UkGRjXirkS9POU/9XwJBnBzViaqvmCdH/zAfy54M/qbqETbDs/K/ox6y0b+6zZwR92zROTrDx8qbw/QG6BcCVC+SuBUsg+3tqtvtIc9wbfL1WC7Q5eio3R8ZiaODdVr2cO6T23OFAlRI34lT0VPIuYbotRInqYOw1NuMRJNhcG1eSyHMaDpFAgMBAAECggEAX12d0PRk6mMjxYg7+7IfmFMnJjABAzgD3V402punh6MO/DnB4XnQjrYLfSQB18u8rePOf6WGRCq2ho5ugBKvrqTQgXVYIZDzm2HwKuiVth5KfjPtu+mIm+A52S8VVtQH2E2TMeDvv7lCqj5mjB/LgapNIj1Zwh3onrs2CF0CW5BRHetuIbJ3fAoPuickxU7djyCoYmA90N0fb/O4ek2XXDfw8nmdaYtXScHudKmmhqvo+0InINNVnzVP6dp2PGaSjpRRAU6cnndCmJ90fzZCyS+8T08e6ypT+SMXk5vNBAxNUb+7Lwfpb0paLCwnLtzfTlUByhRss6njjaB2T/jTAQKBgQDRE2UfUVo68+Ioy9PyzcTJtkL1Qm22bPXbjxfhpJm8g5/dK+dHoVRuQyyNn6VFfnXV8uzfHZlWjvqJk5HtJB7UIChZ86UC2308jAo5S8Xh76RqoMwsNNwSC9tDMqytK0FXvoSdtz7LVabm6PKEtrb0lbfh8eTp3ezjNBXcV+7QNQKBgQDQyy1eifxG6LCt6TKG3/v3zbQhllCh94RdL8JRlk0hzHzAi9fVwUtapC2FYaGgKwNW3nXIiOccZ/yXclKbF11B4usj3dTDjNbHOynwRuMM9Sjox3JaGGrbbebhrFBExewdKIHjUpHb9o11y1vwZ/NwGYvjyhri3ukLqbgUXTUj0QKBgQCvIC7Q18TbopMqluj29VLDnw5g/36EkqoxeZ+IWuaHWD1c9jxo7IKbRVsZWcMG/dFYH343uURKk8LZ4CkYWOwVxMXn6sSqKw2w3KBns8eR47h1tDCxSqmX2CSWGek3uAaop6XPscFAcoM14aPadG21W39GG+ch2cll2qgBBAq+jQKBgEoOVpg6nvVToR7+IILAPTGmj2Z+VzkrfpJC10xy4AbF7dWphDN37M9IfjDZ8SbLOtL78pDfJgHoTCo3TV9fCR/OaZJ+IvH9KUzfCkAEFJJK/miaHVAhav1LXOHcaVgLT3UEIhXL+ponOAN4zrJVXH39QaXY0HJ5l/UgDH+Ek82RAoGANbDw35L/GVBZVxauqKp8l01pmcQjtFe4Kp3rh5+IL3pxNU3f7jftNIj3au8abeEWVJzklBBFV3J3uAXOD7sGmGP4ASr1PMnOdPhUnMaDAgG4zAHC2G+7QiB7dQ9ARCm9rwdERAHfNM7fWzSALC15+xTwN1EDY91QRUlqLVZdYaA=
     alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlrSiZe+OPD94yMdX8R8Tts3Mhn4aqLqFKYgtRIdpClbbNLbhr3YW+bqw3m02jSkcFjg0rdkJ/TWkWlmkteAAReqpcEUgwJ3qEsMUi8nHClT9/DC2ajrlVsUKvtyg13U6C39B98UjLShXa8aAIrpclngE1GplpsiABL1K/aWM++1YSWpLTeMFAElW+6d27367KHoSmsiv26IcJY91gUXjjgSWmdeT8+rSW82VSEaZ9goIvswOCI2JKnnnS/AX5vmt4FzV/AcSlMaHgRc7pfa/Fo+S+s7XNqxzjbrjhAsTs6YNhNDgFUM0QrZ5S3sr6FpYnfjzydcrPPh0Yn8WkViHzwIDAQAB
     signType: RSA2


app-config:
  deposit: 1
  subject: 零零智能手推车押金
  envSecure: 1122334455667788



logging:
  config: classpath:logback-pro.xml