spring:
  datasource:
    url: jdbc:mysql://mysql:3306/goshopping?characterEncoding=utf-8
    username: goshopping
    password: goshoppingpasswd..
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rinlink.goshopping.model
  type-handlers-package: com.rinlink.goshopping.typehandler



rinlink:
   alipay-client:

     #小程序
     gateway: https://openapi.alipay.com/gateway.do
     appId: 2019041963949949
     privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqhbGYQIXfXkeG8VfIOLzv18PUd0qlZx1KBf6NiiupsDK7MVqggRb/PGPuHandSJZgR39Io99S5nSDHy/K0EBhJTxrNnaQK4IjvnsvwIc2iS6a0ugq2jsZg32JjCgpMNrmaxWmAtxwYB/8bmsT6JXCocFWfKImqhu/UkGRjXirkS9POU/9XwJBnBzViaqvmCdH/zAfy54M/qbqETbDs/K/ox6y0b+6zZwR92zROTrDx8qbw/QG6BcCVC+SuBUsg+3tqtvtIc9wbfL1WC7Q5eio3R8ZiaODdVr2cO6T23OFAlRI34lT0VPIuYbotRInqYOw1NuMRJNhcG1eSyHMaDpFAgMBAAECggEAX12d0PRk6mMjxYg7+7IfmFMnJjABAzgD3V402punh6MO/DnB4XnQjrYLfSQB18u8rePOf6WGRCq2ho5ugBKvrqTQgXVYIZDzm2HwKuiVth5KfjPtu+mIm+A52S8VVtQH2E2TMeDvv7lCqj5mjB/LgapNIj1Zwh3onrs2CF0CW5BRHetuIbJ3fAoPuickxU7djyCoYmA90N0fb/O4ek2XXDfw8nmdaYtXScHudKmmhqvo+0InINNVnzVP6dp2PGaSjpRRAU6cnndCmJ90fzZCyS+8T08e6ypT+SMXk5vNBAxNUb+7Lwfpb0paLCwnLtzfTlUByhRss6njjaB2T/jTAQKBgQDRE2UfUVo68+Ioy9PyzcTJtkL1Qm22bPXbjxfhpJm8g5/dK+dHoVRuQyyNn6VFfnXV8uzfHZlWjvqJk5HtJB7UIChZ86UC2308jAo5S8Xh76RqoMwsNNwSC9tDMqytK0FXvoSdtz7LVabm6PKEtrb0lbfh8eTp3ezjNBXcV+7QNQKBgQDQyy1eifxG6LCt6TKG3/v3zbQhllCh94RdL8JRlk0hzHzAi9fVwUtapC2FYaGgKwNW3nXIiOccZ/yXclKbF11B4usj3dTDjNbHOynwRuMM9Sjox3JaGGrbbebhrFBExewdKIHjUpHb9o11y1vwZ/NwGYvjyhri3ukLqbgUXTUj0QKBgQCvIC7Q18TbopMqluj29VLDnw5g/36EkqoxeZ+IWuaHWD1c9jxo7IKbRVsZWcMG/dFYH343uURKk8LZ4CkYWOwVxMXn6sSqKw2w3KBns8eR47h1tDCxSqmX2CSWGek3uAaop6XPscFAcoM14aPadG21W39GG+ch2cll2qgBBAq+jQKBgEoOVpg6nvVToR7+IILAPTGmj2Z+VzkrfpJC10xy4AbF7dWphDN37M9IfjDZ8SbLOtL78pDfJgHoTCo3TV9fCR/OaZJ+IvH9KUzfCkAEFJJK/miaHVAhav1LXOHcaVgLT3UEIhXL+ponOAN4zrJVXH39QaXY0HJ5l/UgDH+Ek82RAoGANbDw35L/GVBZVxauqKp8l01pmcQjtFe4Kp3rh5+IL3pxNU3f7jftNIj3au8abeEWVJzklBBFV3J3uAXOD7sGmGP4ASr1PMnOdPhUnMaDAgG4zAHC2G+7QiB7dQ9ARCm9rwdERAHfNM7fWzSALC15+xTwN1EDY91QRUlqLVZdYaA=
     alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlrSiZe+OPD94yMdX8R8Tts3Mhn4aqLqFKYgtRIdpClbbNLbhr3YW+bqw3m02jSkcFjg0rdkJ/TWkWlmkteAAReqpcEUgwJ3qEsMUi8nHClT9/DC2ajrlVsUKvtyg13U6C39B98UjLShXa8aAIrpclngE1GplpsiABL1K/aWM++1YSWpLTeMFAElW+6d27367KHoSmsiv26IcJY91gUXjjgSWmdeT8+rSW82VSEaZ9goIvswOCI2JKnnnS/AX5vmt4FzV/AcSlMaHgRc7pfa/Fo+S+s7XNqxzjbrjhAsTs6YNhNDgFUM0QrZ5S3sr6FpYnfjzydcrPPh0Yn8WkViHzwIDAQAB
     signType: RSA2

logging:
  config: classpath:logback-pro.xml