spring:
  kafka:
    consumer:
      group-id: ccbaudiodata
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: kafka1:9092

bugkiller:
  mqtt:
    server: emqx
    port: 1883
#    username: testclient
#    password: 9725aa06e172b97f5b631283b59d1a28fca623ad3c3e727b0af53927aab0d131

rinlink:
  thread-pool:
    corePoolSize: 150
    maxPoolSize: 300
    queueCapacity: 50
    keepAliveMilliSecond: 300000

logging:
  config: classpath:logback-pro.xml