server:
  servlet:
    context-path: /v1.0
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/test
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: 1
    template:
      default-topic: async-iot-device-data

logging:
  config: classpath:logback-pro.xml

